### ISSUE TITLE
output dimension of zsl-model

### ISSUE THREAD

**Issue by zhenfelix** [cetinsamet/zero-shot-learning#1]
line 182 in train.py   
out = model.layers[-1].output
->
out = model.layers[-2].output

**Comment by cetinsamet** [comment]
(1) model.layers.pop()
    (2) inp         = model.input
    (3) out         = model.layers[-1].output
    (4) zsl_model   = Model(inp, out)
    (5) #print(zsl_model.summary)
    (6) save_keras_model(zsl_model, model_path=MODELPATH)

Actually, there is nothing wrong related to the output dimension of the zero-shot model.   
At line (1), the outer layer of the _supervised model_ is popped off. At that point, _model_ is the exact zero-shot model that we want to build. However, I preferred to create a new model object, _zsl_model_ namely, and use it for evaluation part to make the code much more understandable.  
  
As I review, I realized that it becomes much more confusing.
So, I optimized it as the following.

    (1) inp         = model.input
    (2) out         = model.layers[-2].output
    (3) zsl_model   = Model(inp, out)
    (4) #print(zsl_model.summary)
    (5) save_keras_model(zsl_model, model_path=MODELPATH)
Best.

**Comment by WangMan1116** [comment]
Hello. Thanks for sharing your code. Based on the above, there is still a dimension problem.Can you provide some solution?Thanks

![Image](https://github.com/user-attachments/assets/e0abb154-96de-4878-b969-bd4f627b746e)
